GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Order pizza"
}

###

DELETE  http://localhost:3001/todo/delete/637e0297751763cfb5160e9b

###

PUT http://localhost:3001/todo/complete/637dfeccabaf653732d36760